pipeline {

    agent {
        docker {
            image 'node:lts-alpine'
        }
    }

    options {
        buildDiscarder(logRotator(numToKeepStr:'10'))
        timeout(time: 5, unit: 'MINUTES')
    }

    stages {
        stage('Install dependencies') {
            steps {
                dir('backend') {
                    sh 'npm ci'
                }
            }
        }

        stage('Lint') {
            steps {
                dir('backend') {
                    sh 'npm run lint'
                }
            }
        }

        stage('Run tests') {
            environment {
                MOCHA_REPORTER    = 'mocha-jenkins-reporter'
                JUNIT_REPORT_PATH = 'report.xml'
                MONGO_URI         = 'mongo-uri-placeholder'
                JWT_PUBLIC_KEY    = 'jwt-public-key-placeholder'
                JWT_PRIVATE_KEY   = 'jwt-private-key-placeholder'
            }

            steps {
                dir('backend') {
                    sh "npm install mocha-jenkins-reporter"
                    sh 'npm test'
                }
            }

            post {
                always {
                    junit 'backend/report.xml'
                }
            }
        }
    }
}
