apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: caselabels-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: CORS_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: cors-origins
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: jwt-public-key
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: jwt-private-key
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: mongo-uri
            - name: PATH_PREFIX
              value: /api
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
