apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
data:
  datasources.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        uid: 53d0e212-a596-49e6-968e-038888cd1376
        url: http://prometheus-service:9090
        isDefault: true
        editable: false
        version: 1
      - name: Jaeger
        type: jaeger
        access: proxy
        uid: 17e65cae-df36-4e27-a2a9-46b3ee6b4eba
        url: http://jaeger-service:16686
        isDefault: false
        editable: false
        version: 1
