apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: backend
        static_configs:
          - labels:
              app: backend
          - targets:
              - backend-service:3000
      - job_name: jaeger
        static_configs:
          - labels:
              app: jaeger
          - targets:
              - jaeger-service:14269
      - job_name: prometheus
        static_configs:
          - labels:
              app: prometheus
          - targets:
              - localhost:9090
      - job_name: grafana
        static_configs:
          - labels:
              app: grafana
          - targets:
              - grafana-service:3000
