version: "3"

services:
  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    ports:
      - ${EXPOSED_MONGO_EXPRESS_PORT:-8081}:8081
    links:
      - mongo

  mongo:
    image: mongo:3.6
    environment:
      MONGO_INITDB_DATABASE: caselabels
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - ${EXPOSED_MONGO_PORT:-27017}:27017
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d:ro
